### ISSUE TITLE
How do we adorn Programs with start/end dates?

### ISSUE THREAD

**Issue by ashepherd** [ec-geolink/design#10]
I think this might be through the Event pattern?

**Comment by krisnadhi** [comment]
Program pattern now contains the startsAtDate and endsAtDate properties. The range is owl-time:Instant. We need some additional work to allow date in XML schema format work with this pattern.

**Comment by krisnadhi** [comment]
We use startsOnDate and endsOnDate properties, instead of startsAtDate and endsAtDate
