### ISSUE TITLE
Prototype GeoLink patterns for DataONE data

### ISSUE THREAD

**Issue by mbjones** [ec-geolink/design#19]
The GeoLink patterns at http://schema.geolink.org need to be applied to the DataONE data sources.  Create an initial mapping for review by the project team.

**Comment by mbjones** [comment]
Initial exemplar RDF triples checked in in Turtle and RDF-XML formats in sha 438d3411307da881aacf0a64ec9525d69b9cba51. Needs further refinement and discussion.

**Comment by amoeba** [comment]
@mbjones: While making a fresh Issue for this task, I found this older task on the second page of Issues. Okay if I just do this tracking work here?

This comment tracks the overall progress of finding mappings between metadata concepts present in the DataOne space to ontological concepts described in the GeoLink base ontology. Progress on individual mappings are tracked here and may reference other Issues tracking their progress.

## Dataset Concepts
DataOne | GeoLink | Status | Issue | In view?
----------|----------|----------|----------|---------
submitter | hasSubmitter | Done | #39 |
rightsHolder | hasRightsHolder | Done | #39  |
formatId | hasFormat | Done | #38  |
checksumAlgorithm | hasChecksumAlgorithm | Done | #44 #37 |
checksum | hasChecksum | Done | #44 #37 |
obseletes/obseletesBy | PROV:wasRevisionOf | Done | #36  |
startDate/endDate | hasStartDate/hasEndDate | Done | #30  |
{north,east,south,west}BoundCoord | hasGeometryAsWktLiteral | Done | #29  |

## Digital Object Concepts

```{ttl}
<https://cn.dataone.org/cn/v1/resolve/2e3a1d04d5a28f215052cf3d\u003C/field\u003Ee/data/eml/ecotrends/14907/2/487fc8812e3a1d04d5a28f215052cf3d>
    glview:isPartOf <https://cn.dataone.org/cn/v1/resolve/https://pasta.lternet.edu/package/metadata/eml/ecotrends/14907/2> ;
    a glview:DigitalObject .
```

## File Format Concepts

```{ttl}
<http://schema.geolink.org/dev/voc/dataone/format#018>
    glview:description "Metadata Encoding and Transmission Standard, version 1" ;
    glview:identifier "http://www.loc.gov/METS/" ;
    a glview:Format .
```

**Comment by amoeba** [comment]
DataOne's producer-centric view, located at:

https://github.com/ec-geolink/design/blob/master/patterns/producer-centric-views/dataone.owl

contains four items. Two of these are expansions of a domain (hasStartdate, hasEndDate) and two are new concepts that don't exist in the GeoLink Base Ontology.

I think all four should be migrated into the GeoLink Base Ontology because they have relevance outside of DataOne. Can people take a look and offer some feedback on whether we want these all to live in the GeoLink Base Ontology? If so, I'll migrate them into view.owl (soon to be base.owl).

**Comment by amoeba** [comment]
Added hasLandingPage:xsd:anyURI addeded to let Datasets and DigitalObjects point to their search.dataone.org view.

**Comment by amoeba** [comment]
I haven't been updating the mappings table but many of the mappings are done and additions to the ontology have been made to support our use case. The DataOne graph is being created by the D1 LOD service, https://github.com/ec-geolink/d1lod/, and documentation for the mappings between GeoLink and DataOne exists at https://github.com/ec-geolink/d1lod/blob/master/docs/mappings.md.
