### ISSUE TITLE
glview:nameFamily on https://github.com/ec-geolink/design/blob/master/data/bco-dmo/people.rdf

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#22]
Example: 
<http://geolink.bco-dmo.org/id/person/50381> glview:nameFull "Dr Carin  J. Ashjian" ;
glview:nameGiven "Carin";
glview:namePrefix "Dr" ;
glview:nameFamily "Ashijan";
glview:nameFamily "J" .

I was confused with assigning the string 'J' to nameFamily. So we have two family names here? Shouldn't it be part of given name instead? Admittedly, we didn't say this in the view.owl, so that's partially my fault too.

**Comment by ashepherd** [comment]
fixed #22 see https://github.com/ec-geolink/design/blob/master/data/bco-dmo/people.rdf
