### ISSUE TITLE
Address discrepancy between D1 format types and GeoLink format types

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/design#38]
http://www.essepuntato.it/lode/http://schema.geolink.org/dev/voc/dataone/format.owl

For example, EML 2.0.1 is
http://www.essepuntato.it/lode/http://schema.geolink.org/dev/voc/dataone/format.owl#d4e17

and this is labeled differently than on D1,

https://cn.dataone.org/cn//v1/formats

**Comment by amoeba** [comment]
This is a little more work than just expanding the existing ontology. 

`DigitalObject`'s can have the predicate `hasFormatType` which point to a Class of `FormatType`. In the ontology, the geolink format types are `FormatType` classes, and not instances of a class.

**Comment by amoeba** [comment]
For now I'm creating the D1 format types as instances in the graph which are of their appropriate class. I'm adding a glview;description to the instances too.

I'm not sure if this is the way to do this yet.

**Comment by krisnadhi** [comment]
I think, hasFormatType should have been changed into hasFormat, and FormatType changed into Format. I don’t know if everyone would agree though.

—adila

**Comment by mbjones** [comment]
I looked at the proposed format that Bryce entered in the dataone graph, which looks like this:

```ttl
<CF-1.0>
    glview:description "NetCDF Climate and Forecast Metadata Convention, version 1.0" ;
    a <http://schema.geolink.org/dev/voc/dataone/format#011> .
```

The problem here is that subject is not a URI, and is typed as an instance.  Instead, I think this should be redefined with a glview:Format class that represents formats, and for each Format, we provide FormatType, identifier, and description properties.  Ths would change the examples to be something more like:

```ttl
<http://schema.geolink.org/dev/voc/dataone/format#011>
    a glview:Format ;
    glview:FormatType "DATA" ;
    glview:identifier [
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "CF-1.0" ;
        rdfs:label "CF-1.0"
    ] ;
    glview:description "NetCDF Climate and Forecast Metadata Convention, version 1.0" .
```

**Comment by amoeba** [comment]
Thanks @mbjones. My proposed formats ontology was committed in e7bbb29060e67bc4457b17217d587251b635f239.

Please take a look at the raw file https://github.com/ec-geolink/design/blob/e7bbb29060e67bc4457b17217d587251b635f239/voc/dataone/format.owl as the diff isn't very useful.

It consists of:

- Class `Format`, of which the D1 formats will be instances of
- OP `hasFormat` which has domain Digital Object and range Format
- DP `formatType` which has domain Digital Object and range `string`. I'm happy to change this to an Object Property if you think we'll want that down the road. For D1 datasets, this will be either DATA or METADATA.
- DP `glview:identifier` I extend the glview;identifier collection to include in its domain the class `Format` so your example above can be implemented.

@mbjones @krisnadhi Does this look good?

**Comment by amoeba** [comment]
I've added a script and the resulting graphs under `data/dataone/formats` The script generates RDF/XML and Turtle graphs of the D1 formats using the above ontology. The URIs seem to match those that @robertarko had in the original formats.owl at https://github.com/ec-geolink/design/blob/dbaac112db386776e0c17d891343fb6b10ef5eca/voc/dataone/format.owl so the URIs haven't changed (this seems good).

For example, this is what is contained in the new graph for CDF 1.0 (as @mbjones used above):

```{turtle}
<http://schema.geolink.org/dev/voc/dataone/format#011>
    glview:description "NetCDF Climate and Forecast Metadata Convention, version 1.0" ;
    glview:formatType "DATA" ;
    glview:identifier [
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "CF-1.0" ;
        a datacite:ResourceIdentifier ;
        rdfs:label "CF-1.0"
    ] ;
    a glview:Format .
```

The only difference here is that I made the `identifier` an instance of the class datacite:ResourceIdentifier as @mbjones had done in the other Python script I'm working on.

The full format graphs are in `data/dataone/formats`.

**Comment by mbjones** [comment]
@amoeba This looks good. I only see one issue. I think we should relocate the formats list back into the voc tree, as this is a shared vocabulary for the project to use, rather than DataONE data per se.  This would replace the formats.owl file that @robertarko provided.

**Comment by amoeba** [comment]
@mbjones Sounds like a good idea but I'm unclear on the file structure you want. Do you want the formats RDF/XML graph in `data/dataone/` and the formats ontology in `voc/dataone/`?

**Comment by amoeba** [comment]
The script that generates the formats graph now mints new URIs and keeps track of what URIs have already been minted. See eae552559c7e09478eea95f6067a67537d306dca.

Here's an example set of triples describing EML 2.0.0:

```{ttl}
<http://schema.geolink.org/dev/voc/dataone/format#001>
    glview:description "Ecological Metadata Language, version 2.0.0" ;
    glview:formatType "METADATA" ;
    glview:hasIdentifier [
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "eml://ecoinformatics.org/eml-2.0.0" ;
        a glview:Identifier ;
        rdfs:label "eml://ecoinformatics.org/eml-2.0.0"
    ] ;
    a glview:Format .
```

The GeoLink Base Ontology needs updating to make the above set of triples valid.

- [ ] Change class FormatType to Format
- [ ] Change hasFormatType to a DataType property, domain: Format, range: xsd:string

**Comment by amoeba** [comment]
The work here is done and the shared vocab is under voc/dataone.
