### ISSUE TITLE
add repository role to geolink views

### ISSUE THREAD

**Issue by mbjones** [ec-geolink/design#40]
At Asilomar, we agreed to give greater resolution to repository roles, namely that any given object has:

1. originRepository: the original repository to which a data object was created/assigned/generated
    - Domain: DigitalObject
    - Range: Repository
2. authoritativeRepository: the current repository that is the authoritative curator of an object
    - Domain: DigitalObject
    - Range: Repository
3. replicaRepository: a repository that holds an exact replica of an object
    - Domain: DigitalObject
    - Range: Repository

Need to add these to the view.owl.

**Comment by amoeba** [comment]
Added these two D1 place-holder ontology in 39b62c6a891466c1873e7bfad9d293923ec44cdb. Didn't go so far as to add any axioms.

Should I add these directly to view.owl?

**Comment by mbjones** [comment]
@amoeba Yeah, I think we can go ahead and add those to view.owl as we agreed in Asilomar.  Let's ping @ashepherd and @robertarko to see if they still agree.

**Comment by robertarko** [comment]
Sounds right to me.

PS. Sorry slow responding lately.  Paying closer attention now.

**Comment by amoeba** [comment]
Migrated these object properties into the main view.owl. See https://github.com/ec-geolink/design/commit/771376a573708e50029af49de93f4eafcd00ed0e
