### ISSUE TITLE
dataone: add repository roles to dataone datasets

### ISSUE THREAD

**Issue by mbjones** [ec-geolink/design#41]
Following the typology in #40.

**Comment by amoeba** [comment]
Done, graph looks like this...

    <https://cn.dataone.org/cn/v1/resolve/knb-lter-arc.943.4>
        ...
        doview:authoritativeRepository <urn:node:LTER> ;
        doview:originRepository <urn:node:LTER> ;
        doview:replicaRepository <urn:node:CN>, <urn:node:LTER> ;

I consider this closed as the use of non-URI repositories is something I need to address with the script in general and for concepts outside of repository roles.
