### ISSUE TITLE
Update DataOne graph script with ontology changes from WHOI meeting

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/design#46]
At the August 19/20 WHOI meeting (Notes on Drive), a number of changes were proposed to the base ontology. These ontology changes will require changes to the DataOne graph script:

- [ ] Change identifier to hasIdentifier
- [ ] Change authoritativeRepository to hasAuthoritativeDigitalRepository
- [ ] Change originRepository to hasOriginDigitalRepository
- [ ] Change replicaRepository to hasReplicaDigitalRepository

**Comment by amoeba** [comment]
The above `*Repository` concepts have range of  `Repository`. I'm not sure if we discussed changing Class `Repository` to `DigitalRepository`.

**Comment by mbjones** [comment]
@amoeba I don't think we should, because we should use the same Repository class for Repositories that hold PhysicalSamples as well as DigitalObjects. In the future we could add properties to Repository allowing a description of the scope of their archive, but I don't think that is needed now.

**Comment by amoeba** [comment]
@mbjones That sounds great and makes the most sense to me.

**Comment by amoeba** [comment]
Changes made in 640abefc2fc6ecc3b739a46cdec6cc1b9c1db2d3.
