### ISSUE TITLE
Changing base URI from http://schema.geolink.org/dev/view into http://schema.geolink.org/dev/base/main

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#49]
@amoeba @robertarko @ashepherd @fils 
I created a new branch "view-to-baseonto" to implement results from our Woods Hole meeting

I and @robertarko agreed to use a new base URI for the base ontology to reflect the changing of terminology from the meeting. 

I copied the view.owl into main.owl, and then use http://schema.geolink.org/dev/base/main as the ontology URI. This means changing URIs of all classes/properties/instances occurring in main.owl (from their original URIs in view.owl) and also, if those classes appear in any of the vocabulary OWL files (local.owl, L22.owl, etc.), their URIs will be changed too there.

I am not merging this branch to 'master' yet, so let me know if there's any big problem on anyone's side due to this change.

**Comment by amoeba** [comment]
Looks good to me. Thanks for getting this done.

I see you also made some changes to concepts that relate to identifiers. Do we want `glview:identifier` to be `glview:hasIdentifier`, as per our discussion during the WHOI meeting about the use of 'has'?
