### ISSUE TITLE
Re-align use of datacite ontology for D1 Datasets

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/design#50]
@mbjones mentioned to me that I need to make sure I'm using DataCite's ontology correctly. I took a look at their ontology,

http://www.essepuntato.it/lode/http://purl.org/spar/datacite

and I think the current use:

    glview:hasIdentifier [
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2" ;
        a datacite:ResourceIdentifier ;
        rdfs:label "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
    ] ;

is not entirely what we want.

The GeoLink supports generic identifiers in the form of a string. DataCite supports a much more structured way of attributing identifiers to resources. 

Taking a look at the example graph located at https://github.com/datacite/ontology/blob/master/RDF_mapping_of_DataCitev2.2_XML_example.ttl, we can see how DataCite uses their ontology:

```{rdf}
<http://dx.doi.org/10.1594/WDCC/CCSRNIES_SRES_B2>
    ...
     datacite:hasIdentifier [ rdf:type datacite:PrimaryResourceIdentifier ;
          literal:hasLiteralValue "10.1594/WDCC/CCSRNIES_SRES_B2" ;
          datacite:usesIdentifierScheme datacite:doi ] ;
    ...
    cito:cites [ datacite:hasIdentifer 
          [ rdf:type datacite:ResourceIdentifier ; 
          literal:hasLiteralValue "http://testing.ts/testpub" ;
          datacite:usesIdentifierScheme datacite:urn ] ] ;
```

Following from the above, I suggest the attribution of identifiers to DataSets/DigitalObjects be split across the two ontologies.

**For a glview:Dataset that has a DataOne PID:**

    glview:hasIdentifier "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2" ;
    datacite:hasIdentifier [
        a datacite:AlternativeResourceIdentifier ;
        datacite:usesIdentifierScheme datacite:local-resource-identifier-scheme ;
        literal:hasLiteralValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
    ] ;

**For a glview:Dataset that has a DataOne PID that is also a DOI:**

    glview:hasIdentifier "https://doi.org/XXXXXXXXXX" ;
    datacite:hasIdentifier [
        a datacite:{PrimaryResourceIdentifier} ;
        datacite:usesIdentifierScheme datacite:doi ;
        literal:hasLiteralValue "https://doi.org/XXXXXXXXXX"
    ] ;

The first set of changes to be made have to do with dealing with DOIs versus other types of identifiers:

- DOIs can be of type `datacite:PrimaryResourceIdentifier`
- Other identifiers can be of type `datacite:AlternativeResourceIdentifier`, these include:
  - DataOne PIDs: scheme: local-resource-identifier-scheme
  - URI/URL/URN/ARK/etc: These use their NamedIndividual in the controlled vocabulary

The second set of changes is to use literals to express the identifier, whether DOI or other, when specifying the DataCite identifier's value.

Notes:
- glview has no `hasIdentifier`. This needs to be changed in the base ontology.
- Note that the example from DataCite brings in the Literal ontology from http://www.essepuntato.it/2010/06/literalreification/

**Comment by krisnadhi** [comment]
I dont' understand why the 'current use' of:
```
glview:hasIdentifier [
    glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
    glview:hasIdentifierValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2" ;
    a datacite:ResourceIdentifier ;
    rdfs:label "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
] 
```
is not what we want.

The base ontology did have <code>identifier</code> as a data property with string as range. 
Regarding the issue that the base ontology has no <code>hasIdentifier</code>, we simply change <code>identifier</code> into an object property with range <code>Identifier</code>, which is a new class. 

In any case, together with adding the new class above, we also add <code>hasIdentifierScheme</code> and <code>hasIdentifierValue</code> as data properties, both with <code>Identifier</code> as their domain. The former's range is <code>xsd:anyURI</code>, while the latter's range is <code>xsd:string</code>.

The above is done in the 'view-to-baseonto' branch.

**Comment by amoeba** [comment]
With the properties you added in 4eed90e2f913af2e065757238e1ffcb20a76941e, the above triple is fine.

Do we want the object property `identifier` to be `hasIdentifier` to bring it inline with our choice of using `has*` for properties?

**Comment by krisnadhi** [comment]
I prefer <code>hasIdentifier</code> to make it more uniform, provided that no one is using the 'old' <code>identifier</code> or changing it to <code>hasIdentifier</code> won't break anything on anyone's side.

**Comment by mbjones** [comment]
I think we agreed to consistently use has* for our property names, and that everyoen would change their data outputs to use the new names in the base ontology.  As we are still at a 'dev' level, I don't see a problem with this change, but all of the existing graphs will have to be updated.

**Comment by krisnadhi** [comment]
Okay. Then I'll go ahead with using <code>hasIdentifier</code>

**Comment by amoeba** [comment]
Great, thanks for moving that along.

To make sure I'm handling identifiers in an acceptable way, could one of you take a look at this? Here's an abbreviated set of triples for a DataOne dataset with one of our local PIDs:

```{turtle}
<https://cn.dataone.org/cn/v1/resolve/cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2>
    a glview:Dataset ;
    ...cut..
    glview:hasIdentifier [
        a glview:Identifier ;
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2" ;
        rdfs:label "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
    ] 
    datacite:hasIdentifier [
        a datacite:AlternativeResourceIdentifier ;
        datacite:usesIdentifierScheme datacite:local-resource-identifier-scheme ;
        literal:hasLiteralValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
    ] ;
```

Is that too redundant to use two blank nodes? I could see typing a single blank node for the identifier, typing it as both a `glview:Identifier` and a `datacite:ResourceIdentifier`, and overloading the blank node with concepts from both GeoLink's ontology and DataCites. I've seen that before but I'm not sure it's best practice.

**Comment by robertarko** [comment]
Nice.

I don't think there's anything wrong with creating multiple blank nodes
for glview:hasIdentifier and datacite:hasIdentifier .  That seems 
cleaner than conflating/overtyping a single node .

PS. I expect we'll shortly publish a new "base.owl" file (that replaces
"view.owl"), and a new RDF namespace "glbase:" (that replaces 
"glview:").

**Comment by amoeba** [comment]
Great. @mbjones and I just chatted a few minutes ago and agreed that keeping the blank nodes separate is a good thing. We also agreed that, for now, we will just stick with using `glbase:hasIdentifier` on all of our datasets and not include the extra triple and bnode for `datacite:hasIdentifier` due to high degree of overlap  between the two. We will use the datacite URIs for the schemes, as above.

So the above set of triples will just be:

```{turtle}
<https://cn.dataone.org/cn/v1/resolve/cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2>
    a glview:Dataset ;
    ...cut..
    glview:hasIdentifier [
        a glview:Identifier ;
        glview:hasIdentifierScheme datacite:local-resource-identifier-scheme ;
        glview:hasIdentifierValue "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2" ;
        rdfs:label "cceptan/pasta.lternet.edu/package/metadata/eml/ecotrends/1549/2"
    ] 
```

Thanks for the PS.
