### ISSUE TITLE
Base ontology: Suggest the range of PhysicalSample.hasStratigraphicUnit is a gazetteer of named instances

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#57]
Moved from #52 

@robertarko suggests the range of PhysicalSample.hasStratigraphicUnit is a gazetteer of named instances (eg. from the USGS National Geologic Map Database):

Bonneville Formation
Portland Formation
Gray Gulch Formation
etc.

Doug - comments ?

**Comment by krisnadhi** [comment]
Related to #55

**Comment by krisnadhi** [comment]
Comment from me in #52:
> Do we want to collect this gazetteer instance into a class in the ontology? If yes, we change the property into ObjectProperty. Otherwise, we simply keep the property as a DataProperty with xsd:anyURI as range.

**Comment by krisnadhi** [comment]
@robertarko @fils @sparkji 
Should we create a class called ```StratigraphicUnit``` to capture stratigraphic gazetteer names? 
Or should we simply say that ```hasStratigraphicUnit``` can point to any URIs?

**Comment by sparkji** [comment]
Yes, we should create stratigraphicUnit class to capture stratigraphic
gazetteer names.

**Comment by krisnadhi** [comment]
Are the stratigraphic gazetteer names available as URIs anywhere? Or are they simply string values?

**Comment by sparkji** [comment]
They should be available as both URIs and string value.

**Comment by krisnadhi** [comment]
But having a class StratigraphicUnit implies that all the names have to be available as URIs and string values should not be used (except only as a label), i.e., you cannot have a triple like 
```:sample1 :hasStratigraphicUnit "Portland Formation"```

**Comment by sparkji** [comment]
Ok. Let's create class StratigraphicUnit, and just use URIs for property
hasStratigraphicUnit.

**Comment by krisnadhi** [comment]
Okay. We got an agreement :+1:  In any case, we could still add string information through the labels of the instances. 

StratigraphicUnit is now added to the base ontology.
