### ISSUE TITLE
Base ontology: why is the range of hasElevation set to xsd:string?

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#60]
Moved from #52 

@mbjones asked:
> Question: why is the range of hasElevation set to xsd:string? Shouldn't that be a numeric quantity, and are units implied?

**Comment by krisnadhi** [comment]
From #52 

@sparkji comment: 
> Comments: In SESAR, elevation is a range, we use elevation, elevation_end
and elevation unit to indicate it, so, xsd:string is good for our case, we
could use the format like ' 10 to 100 m' to fill 'hasElevation' property.

**Comment by krisnadhi** [comment]
From #52 
@mbjones: 
> @sparkji thanks for the explanation. Maybe the property should be renamed hasElevationDescription, to differentiate it from a future property that might be more quantitative and constrained.

**Comment by krisnadhi** [comment]
Question from me in #52:
> @sparkji any objection in changing hasElevation to hasElevationDescription?

**Comment by krisnadhi** [comment]
@sparkji, any objection in replacing ```hasElevation``` with ```hasElevationDescription``` with string as the range?

**Comment by sparkji** [comment]
No objection.
On Sep 10, 2015 6:34 PM, "krisnadhi" <notifications@github.com> wrote:
>
> @sparkji, any objection in replacing hasElevation with
hasElevationDescription with string as the range?

**Comment by krisnadhi** [comment]
Done.
