### ISSUE TITLE
Base ontology: Suggest adding union range 'Organization' and 'Repository' for property 'hasPhysicalRepository'

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#63]
From #52 
@sparkji:
> Suggest adding  union range 'Organization' and 'Repository' for property
'hasPhysicalReopsitory'. In SESAR case, users maybe use both, like LDEO, or
LDEO core repository, the former is organization, the latter is repository.

**Comment by krisnadhi** [comment]
My comment in #52:
> This would cause inconsistency with ```hasRepository``` whose range is only ```Repository```. 
Any comments @robertarko ?

**Comment by krisnadhi** [comment]
@robertarko, @sparkji, Shall we expand the range of ```hasRepository``` to also include ```Organization```? This would allow us to expand the range of ```hasPhysicalRepository``` to include ```Organization``` as suggested by @sparkji, while preventing an inconsistency from happening.

**Comment by sparkji** [comment]
Yes, it's good to expand the range of hasRepository to also include
organization.

**Comment by krisnadhi** [comment]
Done.
