### ISSUE TITLE
Base ontology: vocabulary for relationships between two instances of PhysicalSample

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#68]
@sparkji suggested the sample-to-sample relationships:
- hasParentSample
- hasChildSample
- hasSiblingSample

My comment: are these really intended to be exposed? @robertarko?

**Comment by sparkji** [comment]
Forget the other two things, we just need "hasParentSampe", it's enough for using.
Suggest adding property 'hasParentSample' (Datatype: anyURI) for class 'PhysicalSample'.

**Comment by kjano** [comment]
> Suggest adding property 'hasParentSample' (Datatype: anyURI) for class 
> 'PhysicalSample'.

Not sure what you mean?


On 10/07/2015 08:01 AM, Peng wrote:
>
> Forget the other two things, we just need "hasParentSampe", it's 
> enough for using.
> Suggest adding property 'hasParentSample' (Datatype: anyURI) for class 
> 'PhysicalSample'.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ec-geolink/design/issues/68#issuecomment-146222316>.
>


-- 
Krzysztof Janowicz

Geography Department, University of California, Santa Barbara
4830 Ellison Hall, Santa Barbara, CA 93106-4060

Email: jano@geog.ucsb.edu
Webpage: http://geog.ucsb.edu/~jano/
Semantic Web Journal: http://www.semantic-web-journal.net

**Comment by sparkji** [comment]
We need publishing the relationship between two PhysicalSample instances,
like

'Sample A' hasParentSample 'Sample B'
'Sample C' hasParentSample 'Sample B'

From above statements, we could get other relations like 'Sample B'
hasChildSample 'Sample A', 'Sample B' hasChildSample 'Sample C', 'Sample A'
hasSiblingSample 'Sample C'.

So, we just need 'hasParentSample', does make scene?

**Comment by kjano** [comment]
Sure. Have you checked the pattern for PhysicalSample developed by Yingjie?

On 10/07/2015 10:07 AM, Peng wrote:
> We need publishing the relationship between two PhysicalSample instances,
> like
>
> 'Sample A' hasParentSample 'Sample B'
> 'Sample C' hasParentSample 'Sample B'
>
> From above statements, we could get other relations like 'Sample B'
> hasChildSample 'Sample A', 'Sample B' hasChildSample 'Sample C', 
> 'Sample A'
> hasSiblingSample 'Sample C'.
>
> So, we just need 'hasParentSample', does make scene?
>
> On Wed, Oct 7, 2015 at 12:17 PM, kjano <notifications@github.com> wrote:
>
> > > Suggest adding property 'hasParentSample' (Datatype: anyURI) for class
> > > 'PhysicalSample'.
> >
> > Not sure what you mean?
> >
> >
> > On 10/07/2015 08:01 AM, Peng wrote:
> > >
> > > Forget the other two things, we just need "hasParentSampe", it's
> > > enough for using.
> > > Suggest adding property 'hasParentSample' (Datatype: anyURI) for class
> > > 'PhysicalSample'.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/ec-geolink/design/issues/68#issuecomment-146222316>.
> > >
> >
> >
> > --
> > Krzysztof Janowicz
> >
> > Geography Department, University of California, Santa Barbara
> > 4830 Ellison Hall, Santa Barbara, CA 93106-4060
> >
> > Email: jano@geog.ucsb.edu
> > Webpage: http://geog.ucsb.edu/~jano/
> > Semantic Web Journal: http://www.semantic-web-journal.net
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ec-geolink/design/issues/68#issuecomment-146249540>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ec-geolink/design/issues/68#issuecomment-146264017>.
>


-- 
Krzysztof Janowicz

Geography Department, University of California, Santa Barbara
4830 Ellison Hall, Santa Barbara, CA 93106-4060

Email: jano@geog.ucsb.edu
Webpage: http://geog.ucsb.edu/~jano/
Semantic Web Journal: http://www.semantic-web-journal.net

**Comment by sparkji** [comment]
Got it. I always check  main.owl not patterns. So, just need to add
originatesFrom to main.owl, is it right?

**Comment by krisnadhi** [comment]
I’ll update main.owl for this.

**Comment by krisnadhi** [comment]
Done.
