### ISSUE TITLE
Base ontology: Suggest adding new class 'SamplingMethod', adding new property 'hasSamplingMethod' for class 'PhyicalSample'.

### ISSUE THREAD

**Issue by sparkji** [ec-geolink/design#71]

**Comment by krisnadhi** [comment]
What's the difference between SamplingMethod and SamplingProcess? The PhysicalSample pattern that  @YingjieHu already defines SamplingProcess and the relation (Physical derivedUsing SamplingProcess).

**Comment by sparkji** [comment]
'SamplingProcess' is subclass of 'Event' in PhysicalSample pattern.
'SamplingMethod' (CollectionMethod in SESAR) is not 'Event' but method by
which a sample was collected, e.g. dreging, coring, blasting, etc.

I think they are different, please @YingjieHu
<https://github.com/YingjieHu> make
comment.

**Comment by krisnadhi** [comment]
@sparkji is there a controlled, external vocabulary for sampling method?

**Comment by sparkji** [comment]
We have consensus on revised "PhyscalSample" class within last meeting
(DC/ECIP).
I think you could ignore issues about samples I have proposed, just focus
on IGSN kernel.
Any comments, @robertarko <https://github.com/robertarko>?

**Comment by robertarko** [comment]
Agree.
Goal now is to simplify GeoLink PhysicalSample class to align with 
IGSN schema:
http://schema.igsn.org/

Focused on discovery.

Meanwhile we'll push further Sample details into other schemas ,
like SESAR local.

**Comment by krisnadhi** [comment]
My question was precisely because IGSN has a field "collectionMethod" whose values are from methodTypes. The IGSN XML schema seems to point to a restricted set of string values for method types.

**Comment by robertarko** [comment]
Maybe don't need to restrict method in the GeoLink class.
Just allow anyURI.  But as a practical matter, many folks will populate it
with controlled values from IGSN schema.
?

**Comment by krisnadhi** [comment]
anyURI or string? or both?
http://schema.igsn.org/1.0/include/methodType.html provides strings though

**Comment by sparkji** [comment]
I think should be both anyURI and string.

**Comment by krisnadhi** [comment]
Okay. Done!
