### ISSUE TITLE
Separate DataOne graph service into its own repo

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/design#75]
Move the code for the DataOne graph service into its own repo under the ec-geolink organizization. Leave {datasets|people|organizations}.ttl in data/dataone.

**Comment by mbjones** [comment]
Created repository for this work: https://github.com/ec-geolink/d1lod

**Comment by amoeba** [comment]
Closed by 0ed70fdc283b0a1d22d8f0c28bfef7bc650ce417. See https://github.com/ec-geolink/d1lod.
