### ISSUE TITLE
Dataset containment property

### ISSUE THREAD

**Issue by ashepherd** [ec-geolink/design#77]
To add a property saying that a Dataset "is made up of" smaller Datasets. The idea here is "containment/aggregation" and not "related to" i.e. Dataset A and Dataset B are both found in Dataset C. 

Suggest:

geolink:contains
    domain: Dataset
    range: Dataset

The BCO-DMO use case is that Dataset A was collected on Cruise 123; Dataset B was collected on Cruise 789; Dataset C is both Dataset A and Dataset B combined because they used the same instrumentation, measurements, collected under the same Project. 

_:DatasetC geolink:contains _:DatasetA .
_:DatasetC geolink:contains _:DatasetB .

DataONE has a similar case: https://knb.ecoinformatics.org/#view/doi:10.5063/F19Z92TW 

Discussed at: https://docs.google.com/document/d/1c3jMYqjQOzzqAepdPue9GKWO9b8wDiiyHeAL73ittaQ/edit

**Comment by mbjones** [comment]
I support this use case, regardless of how it is implemented.  We have a similar case in DataONE, where the concept of a DataONE DataPackage is recursive, in that one DataPackage can 'contain' another DataPackage.  An example of such a package is shown here:

https://knb.ecoinformatics.org/#view/doi:10.5063/F19Z92TW

In the display, you'll see the 6 contained datasets listed.  I've been wondering how we would represent this in GeoLink.  geolink:contains seems like a fine property.

**Comment by krisnadhi** [comment]
geolink:contains sounds like a rather generic name that people use for a variety of context. Is this intended only for dataset-containment? If so, I'd suggest geolink:containsDataset instead.

**Comment by ashepherd** [comment]
+1

Adam Shepherd
Software Engineer
BCO-DMO | WHOI
ashepherd@whoi.edu
508-289-2772

**Comment by amoeba** [comment]
I'm okay with either `contains` or `containsDataset`, preferring the latter for its specificity and easy comprehension so long as we don't need a containment-type property for a number of other GeoLink classes.

**Comment by krisnadhi** [comment]
So, we're set with ```containsDataset``` then?

**Comment by robertarko** [comment]
Works for me .

**Comment by krisnadhi** [comment]
```containsDataset``` is added to ```main.owl```
