### ISSUE TITLE
Dataset & its documentation

### ISSUE THREAD

**Issue by ashepherd** [ec-geolink/design#78]
Curious about how DataONE is mapping to GeoLink for its Dataset and metadata record.

I'm assuming you have the Dataset object itself (geolink:DigitalObject) and the corresponding EML or ISO (geolink:Document??) and how do you correlate the two. 

The MBL/WHOI Library has a Repository item for a Dataset which contains:

the dataset file (geolink:DigitalObject)
a metadata record (geolink:Document???)
multiple supporting documentation files like PDFs, images, etc (geolink:Document???)

This repository item has a DOI that represents this collection of files.

Any suggestions on how to correlate all of these?

**Comment by amoeba** [comment]
Hey @ashepherd,

We aren't establishing that our datasets have a metadata file directly but are using the information contained in the metadata to flesh out the `glbase:Dataset`. This is essentially saying that the metadata file is the dataset file, and then the dataset/metadata has a set of `glbase:DigitalObject`s.

I'm not currently, but should, find some way of dealing with digital objects that are better typed as `glbase:Document`s like PowerPoint presentations (of which there are only four on DataOne). I think I'm remembering what we decided about `glbase:Document` on a recent call correctly.

Does that make things clear? @mbjones do you think I'm modeling things right?

**Comment by amoeba** [comment]
After talking to @mbjones and reading what I wrote, I think what I said may have been a bit confusing. I'm going to be writing this and more up under data/dataone to be clear about how DataOne concepts map into GeoLink.

The closest concept in DataOne to a `glbase:Dataset` is the [Data Package](https://releases.dataone.org/online/api-documentation-v1.2.0/design/DataPackage.html). Data Packages have at least one metadata file (e.g. EML) which fits the description of a `glbase:DigitalObject` and at least one data file (e.g. CSV) which also fits the description of a `glbase:DigitalObject`. A Data Package can also have files that are not metadata or data, such as PowerPoints, which would be either `glbase:DigitalObject` or `glbase:Document` (I think the latter, if I am remembering our discussion correctly).

The MBL/WHOI 'Repository' sounds similar to a DataOne Data Package, which we are considering to be our `glbase:Dataset`. DataOne data packages even have identifiers which are sometimes DOIs, for which we'd say something like:

```{ttl}
<https://cn.dataone.org/cn/v1/resolve/doi%3A10.6073%2FAA%2Fknb-lter-arc.943.3>
  a glbase:Dataset ;
  glbase:hasIdentifier [
    a glbase:Identifier ;
    glbase:hasIdentifierScheme <datacite:doi> ;
    glbase:hasIdentifierValue '10.6073/AA/knb-lter-arc.943.3'
  ]
```

The above, if it had an EML document and a data file of some sort, would have two `glbase:hasDigitalObject` statements. So it sounds like all is well. Make your 'dataset files' (I assume you mean files like csv's) and metadata records `glbase:DigitalObject`s and then I think your supporting documents might be `glbase:Document`s. Then make your Repositories `glbase:Dataset`s which have `glbase:Identifier`s.

**Comment by ashepherd** [comment]
This is great, Bryce! Thanks for the feedback. 

best, Adam

**Comment by amoeba** [comment]
Just cleaning up old issues. @ashepherd are we all set on this issue? Could you close if you think so?

**Comment by ashepherd** [comment]
closed
