### ISSUE TITLE
Change base URI for https://github.com/ec-geolink/design/blob/master/voc/identifiers.owl

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#85]
Hi @amoeba,

Can we change the base URI of identifiers.owl so that we have the version info like the other OWL files?
Also, since this OWL file does not actually contain identifiers, but rather, identifier schemes, I think it would be more appropriate to rename it as identifierscheme.owl, and use the following as the base URI:
http://schema.geolink.org/1.0/voc/identifierscheme#

We can additionally use idscheme: as the preferred prefix if you like it.

I can go ahead make the changes if you agree with the suggestions above.

**Comment by mbjones** [comment]
@krisnadhi Those sound like good changes to me, and shouldn't be controversial.  @amoeba is out this week, so I'd say you should go ahead with the changes and if he has comments we can address them after he returns.

**Comment by krisnadhi** [comment]
Thanks, @mbjones.
I'll make the changes then.
