### ISSUE TITLE
Is missing ObjectProperty "hasDocument"?

### ISSUE THREAD

**Issue by sparkji** [ec-geolink/design#90]
Could add ObjectProperty "hasDocument", domain:Cruise, etc., range:Document？
For R2R case, we need this property to link cruise and cruise report.

**Comment by krisnadhi** [comment]
Hi Peng,

There should be a property ‘hasCruise’ (domain: Document or Dataset or DigitalObject or PhysicalSample or Dive, range: Cruise) as well as ‘hasDive’ (domain: Document or Dataset or DigitalObject or PhysicalSample) in the GBO. This should suffice for your needs, shouldn’t it?

**Comment by sparkji** [comment]
Got it. Sorry for ignoring these two properties.
