### ISSUE TITLE
move data.geolink.org to UCSB

### ISSUE THREAD

**Issue by mbjones** [ec-geolink/design#91]
Server no longer can operate at Marymount, so has been moved to a VM at UCSB, co-located with harvest.dataone.org).  Configure:
- [x] sparql endpoint
- [x] pubby endpoint

**Comment by mbjones** [comment]
Update on data.geolink.org, given that the old host is now defunct and you repointed the DNS at the UCSB server.  I restarted the http://data.geolink.org apache server at UCSB, and configured a landing page so its clear what is there.  The SPARQL endpoint is up and running, but the pubby browser is not yet working, due to the same redirection loop that Tom and Bryce encountered earlier (see below).  I'll work with Bryce and Tom this week to try to work out what's wrong there.  Bryce and Tom will need to provide a status update as to the state of the data on that host, and whether its the most current.

## Pubby redirect error
When /id is accessed, the proxy directives send the request to Pubby, which sets up a redirection loop which eventually is stopped by the browser.  The URL that ends in the error looks like:

http://128.111.54.116:8080/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/id/page/pubby/id

**Comment by amoeba** [comment]
Oops, this has been all done for some time.
